// framework/src/components/MenuTree/EditableText.vue
<script setup lang="ts">
import {nextTick, ref} from 'vue';
import {type TreeNodeType} from '@/components/MenuTree/types';
import {useDataSources} from '@/stores/dataSource';
import {HandleSingleDoubleClick} from '@/utils';

const props = defineProps<{
  treeNode: TreeNodeType;
}>();

const editing = ref(false);
const editText = ref(props.treeNode.label);
const inputRef = ref();

const showEditBox = () => {
  editing.value = true;
};

const hideEditBox = async () => {
  if (editText.value === '') {
    editing.value = false;
    editText.value = props.treeNode.label;
    return;
  }
  if (props.treeNode.label !== editText.value) {
    // 更新dataSource
    const res = await useDataSources().updateProjectName(props.treeNode.label, editText.value);
    if (!res) {
      editing.value = false;
      editText.value = props.treeNode.label;
    }
  }
  editing.value = false;
};

const enterEditStatus = () => {
  showEditBox();
  nextTick(() => {
    inputRef.value.focus();
  });
};

const handleDoubleClick = () => {
  // Vue不区分单击、双击,为避免单击事件运行，增加额外控制
  HandleSingleDoubleClick.doubleClick(() => {
    enterEditStatus();
  }, 'projectName');
};

const blurInput = () => {
  inputRef.value.blur();
};

</script>

<template>
  <div class="title-box">
    <div v-show="!editing" @dblclick="handleDoubleClick" class="content-text can-right-click">{{ editText }}</div>
    <input v-show="editing" ref="inputRef" type="text" v-model="editText" @click.stop @blur="hideEditBox" @keyup.enter="blurInput" maxlength="500" autofocus>
  </div>
</template>

<style scoped>
.title-box {
    overflow: hidden;
}
.content-text {
    color: var(--mi-text-color-primary);
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
}

.is-baseline > .el-tree-node__content .content-text {
  color: var(--mi-color-primary);
  font-weight: bold;
}
</style>

// modules/framework/src/components/RemoteManager/ProjectContents/EditableText.tsx
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */
import React, { useState, useRef, useEffect } from 'react';
import { Input } from 'ascend-components';
import styled from '@emotion/styled';
import type { InputRef } from 'antd';
import { updateProjectName } from '@/utils/Project';
import { HandleSingleDoubleClick } from 'ascend-utils';

const Container = styled.div`
  .show {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }
  .hide {
    display: none;
  }
  input {
    width: 100% ;
  }
`;

interface IProps {
    text: string;
}
function EditableText({ text = '' }: IProps): JSX.Element {
    const inputRef = useRef<InputRef>(null);
    const [editing, setEditing] = useState(false);
    const [editText, setEditText] = useState(text);
    // 双击进入编辑
    const handleDoubleClick = (): void => {
        // React不区分单击、双击,为避免单击事件运行，增加额外控制
        HandleSingleDoubleClick.doubleClick(() => {
            enterEditMode();
        }, 'projectName');
    };
    const enterEditMode = (): void => {
        setEditText(text);
        setEditing(true);
    };

    // 退出编辑
    const exitEdit = async (): Promise<void> => {
        const trimmedContent = editText.trim();
        if (trimmedContent !== '' && trimmedContent !== text) {
            const success = await updateProjectName(text, editText);
            if (success) {
                setEditing(false);
            }
        } else {
            setEditing(false);
        }
    };

    const blurInput = (): void => {
        inputRef.current?.blur();
    };

    useEffect(() => {
        if (editing) {
            inputRef.current?.focus();
        }
    }, [editing]);

    return <Container>
        <div className={`can-right-click ${editing ? 'hide' : 'show'}`} onDoubleClick={handleDoubleClick}>{ text }</div>
        <Input className={editing ? 'show' : 'hide'}
            ref={inputRef}
            value={editText}
            onChange={(e): void => { setEditText(e.target.value); }}
            onPressEnter={blurInput}
            onBlur={exitEdit}
            onClick={(e): void => { e.stopPropagation(); }}
        />
    </Container>;
};

export default EditableText;
